# Generated by Django 5.2.15 on 2026-06-24 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deepam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PanchangaSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tithi', models.CharField(max_length=50)),
                ('nakshatra', models.CharField(max_length=50)),
                ('yoga', models.CharField(max_length=50)),
                ('karana', models.CharField(max_length=50)),
                ('masa', models.CharField(max_length=50)),
                ('paksha', models.CharField(max_length=50)),
                ('deepam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='deepam.deepam')),
            ],
        ),
    ]
